### ISSUE TITLE
Missing import of real_cnn_model/data/denoise_events

### ISSUE THREAD

**Issue by wzpscott** [82magnolia/ev_tta#2]
Hi, thanks for your great work. 
In Line 10 of ./real_cnn_model/data/imagenet.py, the import of several event filters seems to be missing.

**Comment by tgc1997** [comment]
I have the same question. Can you provide the file named ./real_cnn_model/data/denoise_events.py?

**Comment by 82magnolia** [comment]
Hi all, sorry for the late reply. I just uploaded the missing file: it should be working now.
